talents = float(input("Enter talents:\n"))
print(" ")
pounds = float(input("Enter pounds:\n"))
print(" ")
lots = float(input("Enter lots:\n"))
print(" ")
kilogram_in_float=float((8.512 * talents) + (0.4256 * pounds) + (0.0133 * lots))
kilogram=int(kilogram_in_float)
gram=float((kilogram_in_float-kilogram)*1000)
print("The weight in modern units:")
print(str(kilogram) + " kilograms & " + (f"{gram:0.2f}") + " grams.")